language: node_js
sudo: false
node_js:
- '6.11.0'

before_install:
  - export CHROME_BIN=chromium-browser
#  - npm i -g yarn

before_script:
  - npm prune

install:
#  - yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
